name = "GraphMLReader"
uuid = "8e6830a9-644c-4485-8539-40ee18e3ca8c"
authors = ["Liye <liyezn@outlook.com>"]
version = "0.1.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticGraphs = "4c8beaf5-199b-59a0-a7f2-21d17de635b6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["StaticGraphs", "Test", "SparseArrays", "Distributed", "ArchGDAL", "BenchmarkTools"]
